### ISSUE TITLE
能否根据操作系统更改指令名称？

### ISSUE THREAD

**Issue by hug2008** [Aweme/McImage#1]
def command = "${rootDir.getParentFile().getPath() + '/mctools/'}pngquant .......

例如：
String os = System.getProperty("os.name");
            if (os != null && os.startsWith("Windows"))
            {
                command = "${rootDir.getParentFile().getPath() + '/mctools/'}pngquant_win .....
            }

**Comment by smallSohoSolo** [comment]
目前win是可以使用的，不需要判断就可以

**Comment by smallSohoSolo** [comment]
最新版本已经支持自动优选，升级即可
