### ISSUE TITLE
混淆问题

### ISSUE THREAD

**Issue by jhonween** [Aweme/McImage#3]
你好，我使用了mcImage,当我开启混淆minifyEnabled true的时候，打release包出现问题
但我关闭混淆的时候，却可以正常打包.
这是什么原因？

**Comment by smallSohoSolo** [comment]
您好具体是什么问题？因为我现在开混淆测试没有问题

**Comment by jhonween** [comment]
> java.io.IOException: Failed to read zip file 'D:\MyAndroidProject\app\build\intermediates\transforms\proguard\debug\jars\3\1f\main.jar'.

**Comment by jhonween** [comment]
就只有上面这些提示

**Comment by EvilsoulM** [comment]
@jhonween 麻烦吧build.gradle 里的插件引用发一下～

**Comment by jhonween** [comment]
apply plugin: 'com.android.application'
apply plugin: 'McImage'
import org.aspectj.bridge.IMessage
import org.aspectj.bridge.MessageHandler
import org.aspectj.tools.ajc.Main


buildscript {
    repositories {
        mavenCentral()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        classpath "io.realm:realm-gradle-plugin:3.5.0"
        classpath 'com.antfortune.freeline:gradle:0.8.7'
        classpath 'org.aspectj:aspectjtools:1.8.9'
        classpath 'org.aspectj:aspectjweaver:1.8.9'
        classpath 'com.smallsoho.mobcase:McImage:0.0.4'
    }
}
 McImageConfig {
        isCheck true //default true   是否进行图片大小超标的检查
        isCompress true //default true  是否进行图片压缩
        maxSize 1*1024*1024 //default 1MB  图片大小超标的标准大小
        isWebpConvert false //default true 是否进行对图片的webp处理
        isJPGConvert false //default true 是否对jpg进行webp处理
        enableWhenDebug false //default true 是否在debug的时候启用插件
    }

**Comment by smallSohoSolo** [comment]
插件集成的不对。
buildscript {
repositories {
mavenCentral()
jcenter()
}

dependencies {
    classpath 'com.android.tools.build:gradle:2.3.3'
    classpath "io.realm:realm-gradle-plugin:3.5.0"
    classpath 'com.antfortune.freeline:gradle:0.8.7'
    classpath 'org.aspectj:aspectjtools:1.8.9'
    classpath 'org.aspectj:aspectjweaver:1.8.9'
    classpath 'com.smallsoho.mobcase:McImage:0.0.4'
}
}
这一段放在根项目的build.gradle里面，不能跟application放一起

**Comment by smallSohoSolo** [comment]
如果解决了你的问题请关闭哈

**Comment by jhonween** [comment]
我们的项目目录就是这样的
![1](https://user-images.githubusercontent.com/6483571/29350967-44e17f56-8293-11e7-851b-73360dfaca05.png)

**Comment by jhonween** [comment]
这个build.gradle里面放了根目录也放了其它的配置东西

**Comment by smallSohoSolo** [comment]
apply plugin :"McImage"这句话写在各个module的build.gradle下，然后classplath 那个写在项目的build.gradle感觉你集成的不对。因为我这测试了几个app都是没问题的，而且插件是在混淆之前做处理。应该跟混淆无关

**Comment by jhonween** [comment]
但我在非混淆状态下是可以打包成功的，而且也压缩了大

**Comment by smallSohoSolo** [comment]
把aspectJ注释掉试试

**Comment by jhonween** [comment]
试了下 还是不能打包成功

**Comment by smallSohoSolo** [comment]
亲，要不你把源码下载下来debug下。我这实在是不能复现。。。。

**Comment by jhonween** [comment]
你好，我查了下，我的混淆文件加了
-keep class  com.tencent.** { *;}
-dontwarn com.tencent.**
会打包错误，把这个去掉后，打包居然成功，但不知道为什么会这样，你们也看看到底是什么导致的，McImage适合在添加这串混淆代码导致冲突？

**Comment by smallSohoSolo** [comment]
这不是腾讯的包名吗。。。跟我应该没什么关系。。。

**Comment by smallSohoSolo** [comment]
插件的原理是换图，没有对之间的代码什么的做任何处理，所以应该不会影响这个。

**Comment by jhonween** [comment]
那我就不知道什么原因了

**Comment by jhonween** [comment]
要不我们加下qq聊下，我吧混淆文件发给你下
