### ISSUE TITLE
关于插件配置问题

### ISSUE THREAD

**Issue by jhonween** [Aweme/McImage#4]
enableWhenDebug false //default true 是否在debug的时候启用插件

你好上面我设置了在debug下不启用插件，为啥gradle还会执行一下操作
[Compress][/Users/zhangwei/MonkeyKingTV/build/intermediates/res/merged/appgame/debug/drawable-xxhdpi/follow_play_icon.png][oldInfo: 601][newInfo: 601]
[Compress][/Users/zhangwei/MonkeyKingTV/build/intermediates/res/merged/appgame/debug/drawable-xxhdpi/follow_time_icon.png][oldInfo: 612][newInfo: 612]
[Compress][/Users/zhangwei/MonkeyKingTV/build/intermediates/res/merged/appgame/debug/drawable-xxhdpi/front_photo_eg.png][oldInfo: 61624][newInfo: 61624]
[Compress][/Users/zhangwei/MonkeyKingTV/build/intermediates/res/merged/appgame/debug/drawable-xxhdpi/game_dice_close_black.png][oldInfo: 275][newInfo: 275]
[Compress][/Users/zhangwei/MonkeyKingTV/build/intermediates/res/merged/appgame/debug/drawable-xxhdpi/game_dice_img_result.png][oldInfo: 23137][newInfo: 23137]
[Compress][/Users/zhangwei/MonkeyKingTV/build/intermediates/res/merged/appgame/debug/drawable-xxhdpi/game_h5_help.png][oldInfo: 2559][newInfo: 2344]
[Compress][/Users/zhangwei/MonkeyKingTV/build/intermediates/res/merged/appgame/debug/drawable-xxhdpi/game_rank_record_dimond.png][oldInfo: 1980][newInfo: 1980]
[Compress][/Users/zhangwei/MonkeyKingTV/build/intermediates/res/merged/appgame/debug/drawable-xxhdpi/gift_default.png][oldInfo: 1890][newInfo: 1890]
[Compress][/Users/zhangwei/MonkeyKingTV/build/intermediates/res/merged/appgame/debug/drawable-xxhdpi/gift_default_chat.png][oldInfo: 2625][newInfo: 2625]
[Compress][/Users/zhangwei/MonkeyKingTV/build/intermediates/res/merged/appgame/debug/drawable-xxhdpi/gift_foreground_streamer.png][oldInfo: 9923][newInfo: 9546]
[Compress][/Users/zhangwei/MonkeyKingTV/build/intermediates/res/merged/appgame/debug/drawable-xxhdpi/gift_ic_lian.png][oldInfo: 747][newInfo: 747]
[Compress]

**Comment by smallSohoSolo** [comment]
已修复，谢谢反馈。请更新0.1.0
